
def clean():
    clear = "\n" * 100
    print(clear)

def principalmenu():
    clean()
    print("###############################################################")
    print("#                                                             #")
    print("#                     MENÚ PRINCIPAL                          #")
    print("#                                                             #")
    print("#                ---Mascotas Nintendo---                      #")
    print("#                                                             #")
    print("#*************************************************************#")
    print("#                                                             #")
    print("#                 ¿Qué necesitas hacer?                       #")
    print("#                                                             #")
    print("# 1. Horario de hoy                                           #")
    print("# 2. Ver calendario                                           #")
    print("# 3. Registro citas                                           #")
    print("# 4. Clientes                                                 #")
    print("# 5. Mascotas                                                 #")
    print("#                                                             #")
    print("# 9. Salir                                                    #")
    print("###############################################################")

def altaclien():
    clean()
    print("###############################################################")
    print("#                                                             #")
    print("#                    ALTA DE CLIENTES                         #")
    print("#                                                             #")
    print("#                ---Mascotas Nintendo---                      #")
    print("#                                                             #")
    print("###############################################################")

def bajaclien():
    clean()
    print("###############################################################")
    print("#                                                             #")
    print("#                    BAJA DE CLIENTES                         #")
    print("#                                                             #")
    print("#                ---Mascotas Nintendo---                      #")
    print("#                                                             #")
    print("###############################################################")

def buscaclien():
    clean()
    print("###############################################################")
    print("#                                                             #")
    print("#                  BUSCADOR DE CLIENTES                       #")
    print("#                                                             #")
    print("#                ---Mascotas Nintendo---                      #")
    print("#                                                             #")
    print("#*************************************************************#")
    print("#                                                             #")
    print("#                 ¿Qué necesitas hacer?                       #")
    print("#                                                             #")
    print("# 1. Busqueda por nombre                                      #")
    print("# 2. Busqueda por DNI                                         #")
    print("# 3. Busqueda por num. telefónico                             #")
    print("#                                                             #")
    print("# 9. Atrás                                                    #")
    print("###############################################################")

def menuclien():
    clean()

    print("###############################################################")
    print("#                                                             #")
    print("#                      MENÚ CLIENTES                          #")
    print("#                                                             #")
    print("#                 ---Mascotas Nintendo---                     #")
    print("#                                                             #")
    print("#                                                             #")
    print("#*************************************************************#")
    print("#                                                             #")
    print("#                 ¿Qué necesitas hacer?                       #")
    print("#                                                             #")
    print("# 1. Mostrar clientes                                         #")
    print("# 2. Alta clientes                                            #")
    print("# 3. Baja clientes                                            #")
    print("# 4. Editar clientes                                          #")
    print("# 5. Buscar clientes                                          #")
    print("#                                                             #")
    print("# 9. Atrás                                                    #")
    print("###############################################################")

def menumasc():
    clean()

    print("###############################################################")
    print("#                                                             #")
    print("#                      MENÚ MASCOTAS                          #")
    print("#                                                             #")
    print("#                 ---Mascotas Nintendo---                     #")
    print("#                                                             #")
    print("#                                                             #")
    print("#*************************************************************#")
    print("#                                                             #")
    print("#                 ¿Qué necesitas hacer?                       #")
    print("#                                                             #")
    print("# 1. Mostrar mascotas                                         #")
    print("# 2. Alta mascotas                                            #")
    print("# 3. Baja mascotas                                            #")
    print("# 4. Buscar mascotas                                          #")
    print("#                                                             #")
    print("# 9. Atrás                                                    #")
    print("###############################################################")



def altamasc():
    clean()
    print("###############################################################")
    print("#                                                             #")
    print("#                    ALTA DE MASCOTAS                         #")
    print("#                                                             #")
    print("#                ---Mascotas Nintendo---                      #")
    print("#                                                             #")
    print("###############################################################")

def bajamasc():
    clean()
    print("###############################################################")
    print("#                                                             #")
    print("#                    BAJA DE MASCOTAS                         #")
    print("#                                                             #")
    print("#                ---Mascotas Nintendo---                      #")
    print("#                                                             #")
    print("###############################################################")

def buscamasc():
    clean()
    print("###############################################################")
    print("#                                                             #")
    print("#                  BUSCADOR DE MASCOTAS                       #")
    print("#                                                             #")
    print("#                ---Mascotas Nintendo---                      #")
    print("#                                                             #")
    print("#*************************************************************#")
    print("#                                                             #")
    print("#                 ¿Qué necesitas hacer?                       #")
    print("#                                                             #")
    print("# 1. Busquedas por dueño                                      #")
    print("# 2. Busqueda por nombre                                      #")
    print("# 3. Busqueda por raza                                        #")
    print("# 4. Busqueda por género                                      #")
    print("#                                                             #")
    print("# 9. Atrás                                                    #")
    print("###############################################################")

def editclien():
    clean()

    print("###############################################################")
    print("#                                                             #")
    print("#                    EDICIÓN CLIENTES                         #")
    print("#                                                             #")
    print("#                 ---Mascotas Nintendo---                     #")
    print("#                                                             #")
    print("#                                                             #")
    print("#*************************************************************#")
    print("#                                                             #")
    print("#                 ¿Qué necesitas hacer?                       #")
    print("#                                                             #")
    print("# 1. Mostrar clientes                                         #")
    print("# 2. Alta clientes                                            #")
    print("# 3. Baja clientes                                            #")
    print("# 4. Editar clientes                                          #")
    print("# 5. Buscar clientes                                          #")
    print("#                                                             #")
    print("# 9. Atrás                                                    #")
    print("###############################################################")