def principalmenu():
    print("###############################################################")
    print("#                                                             #")
    print("#                     MENÚ PRINCIPAL                          #")
    print("#                                                             #")
    print("#                ---Mascotas Nintendo---                      #")
    print("#                                                             #")
    print("#*************************************************************#")
    print("#                                                             #")
    print("#                 ¿Qué necesitas hacer?                       #")
    print("#                                                             #")
    print("# 1. Horario de hoy                                           #")
    print("# 2. Ver calendario                                           #")
    print("# 3. Registro citas                                           #")
    print("# 4. Clientes                                                 #")
    print("# 5. Mascotas                                                 #")
    print("#                                                             #")
    print("# 9. Salir                                                    #")
    print("###############################################################")

def altaclien():
    print("###############################################################")
    print("#                                                             #")
    print("#                    ALTA DE CLIENTES                         #")
    print("#                                                             #")
    print("#                ---Mascotas Nintendo---                      #")
    print("#                                                             #")
    print("###############################################################")

def bajaclien():
    print("###############################################################")
    print("#                                                             #")
    print("#                    BAJA DE CLIENTES                         #")
    print("#                                                             #")
    print("#                ---Mascotas Nintendo---                      #")
    print("#                                                             #")
    print("###############################################################")

def buscaclien():
    print("###############################################################")
    print("#                                                             #")
    print("#                  BUSCADOR DE CLIENTES                       #")
    print("#                                                             #")
    print("#                ---Mascotas Nintendo---                      #")
    print("#                                                             #")
    print("#*************************************************************#")
    print("#                                                             #")
    print("#                 ¿Qué necesitas hacer?                       #")
    print("#                                                             #")
    print("# 1. Busqueda por nombre                                      #")
    print("# 2. Busqueda por DNI                                         #")
    print("# 3. Busqueda por num. telefónico                             #")
    print("#                                                             #")
    print("# 9. Atrás                                                    #")
    print("###############################################################")

def menuclien():
    print("###############################################################")
    print("#                                                             #")
    print("#                      MENÚ CLIENTES                          #")
    print("#                                                             #")
    print("#                 ---Mascotas Nintendo---                     #")
    print("#                                                             #")
    print("#                                                             #")
    print("#*************************************************************#")
    print("#                                                             #")
    print("#                 ¿Qué necesitas hacer?                       #")
    print("#                                                             #")
    print("# 1. Mostrar clientes                                         #")
    print("# 2. Alta clientes                                            #")
    print("# 3. Baja clientes                                            #")
    print("# 4. Buscar clientes                                          #")
    print("#                                                             #")
    print("# 9. Atrás                                                    #")
    print("###############################################################")

def menumasc():
    print("###############################################################")
    print("#                                                             #")
    print("#                                                             #")
    print("#                                                             #")
    print("#                ---Mascotas Nintendo---                      #")
    print("#                                                             #")
    print("###############################################################")